baseURL = 'https://einscat.com/'
languageCode = 'en-US'
title = '行知路'

[params]
author = '陆知行'
slogan = '虽千万里，吾往矣' # 'Life is just a joker.' 'Life should be interesting.'

# 如下导航链接，你应该创建对应的 `.md` 文件，以生成对应的页面
# -----------------------------------
# Nav - nav.md or nav/index.md
# Search - search.md or search/index.md
# Archive - archive.md or archive/index.md
# Wiki - posts/wiki.md or wiki/index.md
# About - about.md or about/index.md
# -----------------------------------
# 菜单选项定制，使用 `00、01、23` 等进行选项顺序调整
# 🐶🎉👀💡👓🐌
[params.menu]
[params.menu.00]
active = true
path = '/nav'
en = 'Nav'
zh = '导航'
icon = '🎯'

[params.menu.22]
active = true
path = 'https://notes.einscat.com'
en = 'Notes'
zh = '笔记'
icon = '📜'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
